server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://user-service:3000/api/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users/ {
        proxy_pass http://user-service:3000/api/users/;
        proxy_set_header Host $host;
    }

    location /api/vehicles/ {
        proxy_pass http://vehicle-service:3000/api/vehicles/;
        proxy_set_header Host $host;
    }
}